### ISSUE TITLE
If no MIDI, throws runtime error

### ISSUE THREAD

**Issue by RobCranfill** [RobCranfill/practiceMonitor#1]
It *almost* handles the situation of no MIDI device OK. But when it tries to garbage collect the LCD display object, it does this:

> 
> * Setting backlight off
> Exception ignored in: <function PracticeDisplay.__del__ at 0x75efb3e8>
> Traceback (most recent call last):
>   File "/home/rob/proj/practiceMonitor/PracticeDisplayLCD.py", line 154, in __del__
>   File "/home/rob/proj/practiceMonitor/PracticeDisplayLCD.py", line 148, in set_backlight_on
>   File "/home/rob/proj/practiceMonitor/zenv/lib/python3.11/site-packages/digitalio.py", line 226, in value
>   File "/home/rob/proj/practiceMonitor/zenv/lib/python3.11/site-packages/adafruit_blinka/microcontroller/bcm283x/pin.py", line 61, in value
> RuntimeError: Please set pin numbering mode using GPIO.setmode(GPIO.BOARD) or GPIO.setmode(GPIO.BCM)

So handle this better, somehow.

**Comment by RobCranfill** [comment]
Also display error on LCD for headless op.
